version: '3.1'

volumes:
  pg_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PG_DATA_PATH}
  lk_files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${LK_FILES_PATH}
  web_forms:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${WEB_FORMS}

networks:
  nexus-pht: {}

services:
  db:
    networks:
    - nexus-pht
    image: postgres:14.1
    container_name: labkey_db
    ports:
    - "5432:5432"
    volumes:
    - pg_data:/var/lib/postgresql/data
    restart: always
    environment:
    - POSTGRES_HOST=localhost
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10



  web:
    networks:
    - nexus-pht
    build: 
      context: ./LabKeyCEServer/21.11.4
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB} 
        SMTP_HOST: ${LABKEY_DEFAULT_DOMAIN}
    image: labkey-ce-server:21.11.4
    container_name: labkey_web
    ports:
    - "8080:8080"
    environment:
    - POSTGRES_HOST=db
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - LABKEY_DEFAULT_DOMAIN
    - SMTP_HOST=intercept-labkey.ethz.ch
    volumes:
    - web_forms:/labkey/server/modules/nexus_external_modules
    - lk_files:/labkey/server/files
    depends_on:
    - db


